apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deploy
spec:
  selector:
    matchLabels:
      app: back-deploy
  template:
    metadata:
      labels:
        app: back-deploy
    spec:
      containers:
      - name: back-deploy
        image: backend:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: back-svc
spec:
  selector:
    app: back-deploy
  ports:
  - port: 3000
    targetPort: 3000

